name: Opcodes generation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Generation C code
      run: ./parse.py -c -chisel -sverilog -rust -latex "rv*" "unratified/rv*"
    - name: Check C output
      run: cat encoding.out.h  | cpp
